
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.108:8501

curl: (3) nested brace in URL position 10:
{columns:[CODE_GENDER_M,EXT_SOURCE_3,EXT_SOURCE_2,NAME_EDUCATION_TYPE_Secondary_or_secondary_special,NAME_EDUCATION_TYPE_Higher_education,NAME_CONTRACT_TYPE_Cash_loans,NAME_INCOME_TYPE_Working],index:[1],data:[[0,0.5108529062,0.6222457753,0,1,1,0]]}}'
         ^
2024-07-11 12:17:57.593 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\u2b50_Global_Feature_Importance.py", line 59, in <module>
    float_1_score = my.get_li_scores(df_selected_record)[0]
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 67, in get_li_scores
    dict_predictions	 = eval(str_dict_predictions) # {"predictions": [0]}
  File "<string>", line 0
    
SyntaxError: invalid syntax
curl: (3) nested brace in URL position 10:
{columns:[CODE_GENDER_M,EXT_SOURCE_3,EXT_SOURCE_2,NAME_EDUCATION_TYPE_Secondary_or_secondary_special,NAME_EDUCATION_TYPE_Higher_education,NAME_CONTRACT_TYPE_Cash_loans,NAME_INCOME_TYPE_Working],index:[1],data:[[0,0.5108529062,0.6222457753,0,1,1,0]]}}'
         ^
2024-07-11 12:20:07.345 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\u2b50_Global_Feature_Importance.py", line 59, in <module>
    float_1_score = my.get_li_scores(df_selected_record)[0]
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 66, in get_li_scores
    debug('str_dict_predictions=[' + ']')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 14, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
2024-07-11 12:29:31.224 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f468\u200d\U0001f3eb_dashboard.py", line 22, in <module>
    my.debug(str_title + ' - Version 0.0.2')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 14, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
2024-07-11 12:29:32.486 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f3b0_simulation.py", line 18, in <module>
    my.debug(str_title + ' - Version 0.0.2')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 14, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
2024-07-11 12:29:38.713 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f3b0_simulation.py", line 18, in <module>
    my.debug(str_title + ' - Version 0.0.2')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 14, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
2024-07-11 12:29:39.912 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f468\u200d\U0001f3eb_dashboard.py", line 22, in <module>
    my.debug(str_title + ' - Version 0.0.2')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 14, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
2024-07-11 12:29:43.512 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f3b0_simulation.py", line 18, in <module>
    my.debug(str_title + ' - Version 0.0.2')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 14, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
curl: (3) nested brace in URL position 10:
{columns:[CODE_GENDER_M,EXT_SOURCE_3,EXT_SOURCE_2,NAME_EDUCATION_TYPE_Secondary_or_secondary_special,NAME_EDUCATION_TYPE_Higher_education,NAME_CONTRACT_TYPE_Cash_loans,NAME_INCOME_TYPE_Working],index:[1],data:[[0,0.5108529062,0.6222457753,0,1,1,0]]}}'
         ^
2024-07-11 12:29:45.987 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\u2b50_Global_Feature_Importance.py", line 59, in <module>
    float_1_score = my.get_li_scores(df_selected_record)[0]
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 66, in get_li_scores
    debug('str_dict_predictions=[' + ']')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 14, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
curl: (3) nested brace in URL position 10:
{columns:[CODE_GENDER_M,EXT_SOURCE_3,EXT_SOURCE_2,NAME_EDUCATION_TYPE_Secondary_or_secondary_special,NAME_EDUCATION_TYPE_Higher_education,NAME_CONTRACT_TYPE_Cash_loans,NAME_INCOME_TYPE_Working],index:[1],data:[[0,0.5108529062,0.6222457753,0,1,1,0]]}}'
         ^
2024-07-11 12:31:31.553 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\u2b50_Global_Feature_Importance.py", line 59, in <module>
    float_1_score = my.get_li_scores(df_selected_record)[0]
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 68, in get_li_scores
    dict_predictions	 = eval(str_dict_predictions) # {"predictions": [0]}
  File "<string>", line 0
    
SyntaxError: invalid syntax
curl: (3) nested brace in URL position 10:
{columns:[CODE_GENDER_M,EXT_SOURCE_3,EXT_SOURCE_2,NAME_EDUCATION_TYPE_Secondary_or_secondary_special,NAME_EDUCATION_TYPE_Higher_education,NAME_CONTRACT_TYPE_Cash_loans,NAME_INCOME_TYPE_Working],index:[1],data:[[0,0.5108529062,0.6222457753,0,1,1,0]]}}'
         ^
2024-07-11 12:32:46.900 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\u2b50_Global_Feature_Importance.py", line 59, in <module>
    float_1_score = my.get_li_scores(df_selected_record)[0]
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 68, in get_li_scores
    dict_predictions	 = eval(str_dict_predictions) # {"predictions": [0]}
  File "<string>", line 0
    
SyntaxError: invalid syntax
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   327  100    37  100   290   2896  22705 --:--:-- --:--:-- --:--:-- 27250
C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\shap\plots\_beeswarm.py:952: UserWarning:

FigureCanvasAgg is non-interactive, and thus cannot be shown

2024-07-11 12:57:36.402 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\u2b50_Global_Feature_Importance.py", line 59, in <module>
    float_1_score = my.get_li_scores(df_selected_record)[0]
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 65, in get_li_scores
    st.write('os.system =[' + os.system + ']')
NameError: name 'os' is not defined
2024-07-11 12:57:51.414 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\u2b50_Global_Feature_Importance.py", line 59, in <module>
    float_1_score = my.get_li_scores(df_selected_record)[0]
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 67, in get_li_scores
    st.write('os.system =[' + os.system + ']')
TypeError: can only concatenate str (not "builtin_function_or_method") to str
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   327  100    37  100   290   3899  30561 --:--:-- --:--:-- --:--:-- 36333
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   327  100    37  100   290   2227  17457 --:--:-- --:--:-- --:--:-- 20437
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   327  100    37  100   290   2069  16221 --:--:-- --:--:-- --:--:-- 19235
2024-07-11 13:02:11.136 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f468\u200d\U0001f3eb_dashboard.py", line 22, in <module>
    my.debug(str_title + ' - Version 0.0.2')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 15, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
2024-07-11 13:02:13.398 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f468\u200d\U0001f3eb_dashboard.py", line 22, in <module>
    my.debug(str_title + ' - Version 0.0.2')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 15, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   327  100    37  100   290   1540  12076 --:--:-- --:--:-- --:--:-- 14217
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 88   330    0     0  100   293      0  14425 --:--:-- --:--:-- --:--:-- 13952100   330  100    37  100   293   1774  14054 --:--:-- --:--:-- --:--:-- 15714
C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\shap\plots\_waterfall.py:315: UserWarning:

FigureCanvasAgg is non-interactive, and thus cannot be shown

2024-07-11 13:04:22.754 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f3b0_simulation.py", line 18, in <module>
    my.debug(str_title + ' - Version 0.0.2')
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 15, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
2024-07-11 13:04:40.994 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Jean\OCR\git\project_8\pages\\U0001f3b0_simulation.py", line 28, in <module>
    df_data.set_index('request_id', inplace=True)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\pandas\core\frame.py", line 6122, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['request_id'] are in the columns"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   330  100    37  100   293   2720  21547 --:--:-- --:--:-- --:--:-- 25384
2024-07-11 13:05:50.588 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 408, in __getitem__
    return self._getitem(widget_id, key)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 453, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 567, in _run_script
    self._session_state.on_script_will_rerun(
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 66, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 514, in on_script_will_rerun
    self._call_callbacks()
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 527, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 271, in call_callback
    callback(*args, **kwargs)
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 86, in display_simulated_score
    df_1_record = st.session_state['df_simulated_record'].copy()
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 98, in __getitem__
    return get_session_state()[key]
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 94, in __getitem__
    return self._state[key]
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 410, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "df_simulated_record". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   330  100    37  100   293    871   6904 --:--:-- --:--:-- --:--:--  7857
2024-07-11 13:19:27.911 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 408, in __getitem__
    return self._getitem(widget_id, key)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 453, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 567, in _run_script
    self._session_state.on_script_will_rerun(
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 66, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 514, in on_script_will_rerun
    self._call_callbacks()
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 527, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 271, in call_callback
    callback(*args, **kwargs)
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 87, in display_simulated_score
    df_1_record = st.session_state['df_simulated_record'].copy()
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 98, in __getitem__
    return get_session_state()[key]
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 94, in __getitem__
    return self._state[key]
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 410, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "df_simulated_record". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   330  100    37  100   293   2243  17762 --:--:-- --:--:-- --:--:-- 20625
2024-07-11 13:21:58.902 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 567, in _run_script
    self._session_state.on_script_will_rerun(
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 66, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 514, in on_script_will_rerun
    self._call_callbacks()
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 527, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "C:\Users\Jean\anaconda3\envs\env_ocr_projet_8\lib\site-packages\streamlit\runtime\state\session_state.py", line 271, in call_callback
    callback(*args, **kwargs)
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 96, in display_simulated_score
    debug(feature + '=' + str(new_value))
  File "C:\Users\Jean\OCR\git\project_8\utils\my_functions.py", line 15, in debug
    with open('./log/streamlit_app.log', 'a') as f:
PermissionError: [Errno 13] Permission denied: './log/streamlit_app.log'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   330  100    37  100   293   2685  21264 --:--:-- --:--:-- --:--:-- 25384
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   324  100    37  100   287   3858  29930 --:--:-- --:--:-- --:--:-- 36000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 88   330    0     0  100   293      0  17637 --:--:-- --:--:-- --:--:-- 17235100   330  100    37  100   293   2178  17249 --:--:-- --:--:-- --:--:-- 19411
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   315  100    36  100   279   4096  31747 --:--:-- --:--:-- --:--:-- 39375
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   330  100    37  100   293   2028  16066 --:--:-- --:--:-- --:--:-- 18333
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   315  100    37  100   278   2163  16258 --:--:-- --:--:-- --:--:-- 18529
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   330  100    37  100   293   1963  15549 --:--:-- --:--:-- --:--:-- 18333
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   316  100    37  100   279   3004  22657 --:--:-- --:--:-- --:--:-- 26333
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   330  100    37  100   293   2272  17998 --:--:-- --:--:-- --:--:-- 20625
